services:
  client:
    build: ./client
    ports:
      - "5173:5173"
    env_file:
      - ./client/.env
    depends_on:
      - server

  server:
    build: ./server
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    depends_on:
      - db
    entrypoint: ["/bin/sh", "-c", "npx prisma migrate deploy && node dist/http/index.js"]

  db:
    image: postgres:15
    env_file:
      - ./server/.env
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
